/* ── Year 1 Maths curriculum data ───────────────────────────────────────── *
 * 59 nuggets covering the full KS1 Year 1 NC programme of study.            *
 * Each nugget: { id, topic, name, obj }                                    */

const NUGGETS = [
  {id:1, topic:'Number – Number & Place Value', name:'Counting forwards 1–20',          obj:'Count to and across 100, forwards and backwards, beginning with 0 or 1, or from any given number'},
  {id:2, topic:'Number – Number & Place Value', name:'Counting backwards 1–20',         obj:'Count to and across 100, forwards and backwards, beginning with 0 or 1, or from any given number'},
  {id:3, topic:'Number – Number & Place Value', name:'Counting forwards 20–100',         obj:'Count to and across 100, forwards and backwards, beginning with 0 or 1, or from any given number'},
  {id:4, topic:'Number – Number & Place Value', name:'Counting backwards 20–100',        obj:'Count to and across 100, forwards and backwards, beginning with 0 or 1, or from any given number'},
  {id:5, topic:'Number – Number & Place Value', name:'Count in multiples of 2',          obj:'Count, read and write numbers to 100 in numerals; count in multiples of twos, fives and tens'},
  {id:6, topic:'Number – Number & Place Value', name:'Count in multiples of 5',          obj:'Count, read and write numbers to 100 in numerals; count in multiples of twos, fives and tens'},
  {id:7, topic:'Number – Number & Place Value', name:'Count in multiples of 10',         obj:'Count, read and write numbers to 100 in numerals; count in multiples of twos, fives and tens'},
  {id:8, topic:'Number – Number & Place Value', name:'One more than',                    obj:'Given a number, identify one more and one less'},
  {id:9, topic:'Number – Number & Place Value', name:'One less than',                    obj:'Given a number, identify one more and one less'},
  {id:10,topic:'Number – Number & Place Value', name:'Counting pictorial representations 1–10',  obj:'Identify and represent numbers using objects and pictorial representations including the number line'},
  {id:11,topic:'Number – Number & Place Value', name:'Counting pictorial representations 11–20', obj:'Identify and represent numbers using objects and pictorial representations including the number line'},
  {id:12,topic:'Number – Number & Place Value', name:'Tens and ones',                    obj:'Identify and represent numbers using objects and pictorial representations including the number line'},
  {id:13,topic:'Number – Number & Place Value', name:'Number line 1–10',                 obj:'Identify and represent numbers using objects and pictorial representations including the number line'},
  {id:14,topic:'Number – Number & Place Value', name:'Number line 11–20',                obj:'Identify and represent numbers using objects and pictorial representations including the number line'},
  {id:15,topic:'Number – Number & Place Value', name:'Equal to, more than, less than, most, least', obj:'Use the language of: equal to, more than, less than (fewer), most, least'},
  {id:16,topic:'Number – Number & Place Value', name:'Read and write numbers 1–20 in numerals and words', obj:'Read and write numbers from 1 to 20 in numerals and words'},
  {id:17,topic:'Number – Addition & Subtraction', name:'Understanding + − =',            obj:'Read, write and interpret mathematical statements involving addition (+), subtraction (−) and equals (=) signs'},
  {id:18,topic:'Number – Addition & Subtraction', name:'Number bonds to 10',             obj:'Represent and use number bonds and related subtraction facts within 20'},
  {id:19,topic:'Number – Addition & Subtraction', name:'Number bonds to 20',             obj:'Represent and use number bonds and related subtraction facts within 20'},
  {id:20,topic:'Number – Addition & Subtraction', name:'Adding up to 10',                obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:21,topic:'Number – Addition & Subtraction', name:'Subtracting up to 10',           obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:22,topic:'Number – Addition & Subtraction', name:'Adding up to 10 with pictorial representations',    obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:23,topic:'Number – Addition & Subtraction', name:'Subtracting up to 10 with pictorial representations',obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:24,topic:'Number – Addition & Subtraction', name:'Adding up to 10 with number lines',    obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:25,topic:'Number – Addition & Subtraction', name:'Subtracting up to 10 with number lines',obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:26,topic:'Number – Addition & Subtraction', name:'Adding up to 10 abstract',       obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:27,topic:'Number – Addition & Subtraction', name:'Subtracting up to 10 abstract',  obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:28,topic:'Number – Addition & Subtraction', name:'Adding up to 20 with pictorial representations',    obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:29,topic:'Number – Addition & Subtraction', name:'Subtracting up to 20 with pictorial representations',obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:30,topic:'Number – Addition & Subtraction', name:'Adding up to 20 with number lines',    obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:31,topic:'Number – Addition & Subtraction', name:'Subtracting up to 20 with number lines',obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:32,topic:'Number – Addition & Subtraction', name:'Adding up to 20 abstract',       obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:33,topic:'Number – Addition & Subtraction', name:'Subtracting up to 20 abstract',  obj:'Add and subtract one-digit and two-digit numbers to 20, including zero'},
  {id:34,topic:'Number – Addition & Subtraction', name:'Addition word problems 1–20 with pictorial representations',    obj:'Solve one-step problems that involve addition and subtraction, using concrete objects and pictorial representations'},
  {id:35,topic:'Number – Addition & Subtraction', name:'Subtraction word problems 1–20 with pictorial representations', obj:'Solve one-step problems that involve addition and subtraction, using concrete objects and pictorial representations'},
  {id:36,topic:'Number – Addition & Subtraction', name:'Mixed word problems 1–20 with pictorial representations',       obj:'Solve one-step problems that involve addition and subtraction, using concrete objects and pictorial representations'},
  {id:37,topic:'Number – Addition & Subtraction', name:'Missing number problems',         obj:'Solve missing number problems such as 7 = □ − 9'},
  {id:38,topic:'Number – Multiplication & Division', name:'Multiplying by 2 with pictorial representations / arrays', obj:'Solve one-step problems involving multiplication and division, using concrete objects, pictorial representations and arrays'},
  {id:39,topic:'Number – Multiplication & Division', name:'Multiplying by 5 with pictorial representations / arrays', obj:'Solve one-step problems involving multiplication and division, using concrete objects, pictorial representations and arrays'},
  {id:40,topic:'Number – Multiplication & Division', name:'Multiplying by 10 with pictorial representations / arrays',obj:'Solve one-step problems involving multiplication and division, using concrete objects, pictorial representations and arrays'},
  {id:41,topic:'Number – Fractions', name:'Recognise and find a half',    obj:'Recognise, find and name a half as one of two equal parts of an object, shape or quantity'},
  {id:42,topic:'Number – Fractions', name:'Recognise and find a quarter', obj:'Recognise, find and name a quarter as one of four equal parts of an object, shape or quantity'},
  {id:43,topic:'Measurement', name:'Describing and comparing length',           obj:'Compare, describe and solve practical problems for lengths and heights'},
  {id:44,topic:'Measurement', name:'Describing and comparing mass',             obj:'Compare, describe and solve practical problems for mass/weight'},
  {id:45,topic:'Measurement', name:'Describing and comparing volume and capacity', obj:'Compare, describe and solve practical problems for capacity and volume'},
  {id:46,topic:'Measurement', name:'Describing and comparing time',             obj:'Compare, describe and solve practical problems for time'},
  {id:47,topic:'Measurement', name:'Measure with blocks',                        obj:'Measure and begin to record lengths and heights'},
  {id:48,topic:'Measurement', name:'Measure with cm up to 30 cm',               obj:'Measure and begin to record lengths and heights'},
  {id:49,topic:'Measurement', name:'Measure mass (multiples of 10g up to 100g)',obj:'Measure and begin to record mass/weight'},
  {id:50,topic:'Measurement', name:'Measure litres 1–10',                       obj:'Measure and begin to record capacity and volume'},
  {id:51,topic:'Measurement', name:'Measure time (hours minutes seconds)',       obj:'Measure and begin to record time (hours, minutes, seconds)'},
  {id:52,topic:'Measurement', name:'Recognising coins and notes',               obj:'Recognise and know the value of different denominations of coins and notes'},
  {id:53,topic:'Measurement', name:'Sequencing events',                         obj:'Sequence events in chronological order using language'},
  {id:54,topic:'Measurement', name:'Days of the week',                          obj:'Recognise and use language relating to dates, including days of the week, weeks, months and years'},
  {id:55,topic:'Measurement', name:'Months of the year',                        obj:'Recognise and use language relating to dates, including days of the week, weeks, months and years'},
  {id:56,topic:'Measurement', name:'Tell the time to the hour and half past',   obj:'Tell the time to the hour and half past the hour and draw the hands on a clock face'},
  {id:57,topic:'Geometry – Properties of Shapes', name:'Recognise and name common 2-D shapes', obj:'Recognise and name common 2-D shapes (rectangles, squares, circles, triangles)'},
  {id:58,topic:'Geometry – Properties of Shapes', name:'Recognise and name common 3-D shapes', obj:'Recognise and name common 3-D shapes (cuboids, cubes, pyramids, spheres)'},
  {id:59,topic:'Geometry – Position & Direction', name:'Position and direction', obj:'Describe position, direction and movement, including whole, half, quarter and three-quarter turns'},
];

const TOPICS = [...new Set(NUGGETS.map(n => n.topic))];

const STATUS_LABELS = {
  'not-started':    'Not started',
  'in-progress':    'In progress',
  'ready-for-qa':   'Ready for QA',
  'ready-for-qti':  'Ready for QTI',
  'uploaded-to-cms':'Uploaded to CMS',
};

const STATUS_CM = {
  'not-started':    'ns',
  'in-progress':    'ip',
  'ready-for-qa':   'qa',
  'ready-for-qti':  'rd',
  'uploaded-to-cms':'up',
};
